import { pool } from '../db/index.js';
import { getSiteOwnerTierLimits, getUserTierLimits } from './site.service.js';
import type { OrgBranding } from '../types/organization.types.js';

interface SiteBrandingFields {
  companyName?: string;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  footerText?: string;
}

export interface ResolvedBranding {
  companyName: string;
  logoUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  footerText: string;
  canExportPdf: boolean;
  canWhiteLabel: boolean;
}

const DEFAULTS: ResolvedBranding = {
  companyName: 'Kritano',
  logoUrl: null,
  primaryColor: '#4f46e5',
  secondaryColor: '#6366f1',
  accentColor: '#f59e0b',
  footerText: 'Generated by Kritano',
  canExportPdf: false,
  canWhiteLabel: false,
};

/**
 * Resolve PDF branding based on tier and site/org settings.
 *
 * Resolution chain:
 * 1. Get tier via site owner or user
 * 2. export_pdf === false (free) → defaults with canExportPdf: false
 * 3. white_label === false (starter/pro) → site colors + name, footer = "Generated by Kritano", no logo
 * 4. white_label === true (agency+) → load org branding, merge site overrides, custom footer, logo
 */
export async function resolvePdfBranding(
  siteId: string | null,
  userId: string
): Promise<ResolvedBranding> {
  // 1. Get tier limits — prefer site-owner-based resolution
  const tierLimits = siteId
    ? await getSiteOwnerTierLimits(siteId)
    : await getUserTierLimits(userId);

  const exportPdf = tierLimits?.export_pdf as boolean ?? false;
  const whiteLabel = tierLimits?.white_label as boolean ?? false;

  // 2. Free tier — no PDF export
  if (!exportPdf) {
    return { ...DEFAULTS };
  }

  // Load site branding if site exists and is verified
  let siteBranding: SiteBrandingFields | null = null;
  let siteOrgId: string | null = null;

  if (siteId) {
    const siteResult = await pool.query<{
      verified: boolean;
      organization_id: string | null;
      settings: {
        branding?: SiteBrandingFields;
      } | null;
    }>(
      `SELECT verified, organization_id, settings FROM sites WHERE id = $1`,
      [siteId]
    );

    if (siteResult.rows.length > 0) {
      const site = siteResult.rows[0];
      siteOrgId = site.organization_id;
      if (site.verified && site.settings?.branding) {
        siteBranding = site.settings.branding;
      }
    }
  }

  // 3. Starter/Pro — site branding only, forced Kritano footer, no logo
  if (!whiteLabel) {
    return {
      companyName: siteBranding?.companyName || DEFAULTS.companyName,
      logoUrl: null,
      primaryColor: siteBranding?.primaryColor || DEFAULTS.primaryColor,
      secondaryColor: siteBranding?.secondaryColor || DEFAULTS.secondaryColor,
      accentColor: siteBranding?.accentColor || DEFAULTS.accentColor,
      footerText: 'Generated by Kritano',
      canExportPdf: true,
      canWhiteLabel: false,
    };
  }

  // 4. Agency+ — load org branding as base, site overrides on top
  let orgBranding: OrgBranding | null = null;

  if (siteOrgId) {
    const orgResult = await pool.query<{
      settings: { branding?: OrgBranding } | null;
    }>(
      `SELECT settings FROM organizations WHERE id = $1`,
      [siteOrgId]
    );

    if (orgResult.rows.length > 0 && orgResult.rows[0].settings?.branding) {
      orgBranding = orgResult.rows[0].settings.branding;
    }
  }

  // Merge: org branding as base, site branding overrides where set
  const base: OrgBranding = orgBranding || {};
  const override: SiteBrandingFields = siteBranding || {};

  return {
    companyName: override.companyName || base.companyName || DEFAULTS.companyName,
    logoUrl: override.logoUrl || base.logoUrl || null,
    primaryColor: override.primaryColor || base.primaryColor || DEFAULTS.primaryColor,
    secondaryColor: override.secondaryColor || base.secondaryColor || DEFAULTS.secondaryColor,
    accentColor: override.accentColor || base.accentColor || DEFAULTS.accentColor,
    footerText: override.footerText || base.footerText || DEFAULTS.footerText,
    canExportPdf: true,
    canWhiteLabel: true,
  };
}
